<?xml version="1.0" encoding="UTF-8"?><testrun name="ChercherDichoEtuRecTest" project="TP2-2" tests="7" started="7" failures="1" errors="0" ignored="0">
  <testsuite name="test.java.ChercherDichoEtuRecTest" time="0.027">
    <testcase name="chercherDichoEtuRecElementWrongNumber" classname="test.java.ChercherDichoEtuRecTest" time="0.005"/>
    <testcase name="chercherDichoElementMini" classname="test.java.ChercherDichoEtuRecTest" time="0.002"/>
    <testcase name="chercherDichoEtuRecElementWrongPrice" classname="test.java.ChercherDichoEtuRecTest" time="0.001"/>
    <testcase name="chercherDichoEtuRecElementNotInTableTest" classname="test.java.ChercherDichoEtuRecTest" time="0.001"/>
    <testcase name="chercherDichoEtuRecElementInTableTest" classname="test.java.ChercherDichoEtuRecTest" time="0.0"/>
    <testcase name="chercherDichoElementMax" classname="test.java.ChercherDichoEtuRecTest" time="0.01">
      <failure>java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at test.java.ChercherDichoEtuRecTest.chercherDichoElementMax(ChercherDichoEtuRecTest.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

</failure>
    </testcase>
    <testcase name="chercherDichoEtuRecElementWrongName" classname="test.java.ChercherDichoEtuRecTest" time="0.003"/>
  </testsuite>
</testrun>
