package test.java;

import static org.junit.Assert.*;

import java.util.concurrent.CountDownLatch;

import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.Timeout;
import org.junit.runners.model.TestTimedOutException;

import main.java.Article;
import main.java.Magasin;
import sun.util.logging.resources.logging;


import org.junit.Test;

public class ChercherDicho2Test {
	
	private final CountDownLatch latch = new CountDownLatch(1);
	
	private Article articleValid;
	private Article articleValid2;
	private Article articleValid3;
	private Article articleToFind;
	private Magasin magasin;
	
	@Rule
	public Timeout globalTimeout = Timeout.seconds(10);

	@Before
	public void setUp() throws Exception {
		articleValid = new Article("Article1", 50, 1);
		articleValid2 = new Article("Article2", 51, 2);
		articleValid3 = new Article("Article3", 52, 3);
		articleToFind = new Article("ToFind", 52, 4);
		magasin = new Magasin(3);
		magasin.insererArticle(articleValid);
		magasin.insererArticle(articleValid2);
		magasin.insererArticle(articleValid3);
		
		//System.out.println("Appel de setUp() - @Before");
	}	

	@Test
	public void chercherDicho2PriceMatchWrongNumber() {
		assertFalse(magasin.chercherDicho2(articleToFind));
	}

}
